version: '3'
services:
  db: 
    image: postgres:11.21-bullseye
    environment:
        POSTGRES_USER: cartease
        POSTGRES_PASSWORD: cartease@123
        POSTGRES_DB: db
    ports:
      - 5432:5432
  app-production:
    environment:
      DATABASE_URL: postgresql://cartease:cartease@123@db:5432/db?schema=public
    build:
      dockerfile: ./Dockerfile.production
    depends_on:
      - db
    ports:
      - 3000:3000
  app-develop:
    environment:
      DATABASE_URL: postgresql://cartease:cartease@123@db:5432/db?schema=public
    build:
      dockerfile: ./Dockerfile.develop
    depends_on:
      - db
    ports:
      - 3000:3000
    volumes:
      - .:/app